---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: contenu
  label: Home
  create: all
  match: "*"
- type: directory
  path: contenu/creations
  label: Creations
  create: all
  match: "**/*"
- type: directory
  path: contenu/products
  label: Produits
  create: all
  match: "**/*"
- type: directory
  path: contenu/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: contenu/.vuepress/public
public_path: contenu/.vuepress/dist
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
